name: jslint

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: curl -L https://www.jslint.com/jslint.mjs > jslint.mjs
    - name: Run JSLint
      run: node jslint.mjs src/flickypedia/static/flickypedia.js
